### ISSUE TITLE
Bridge crashes: segmentation violation code=0x1

### ISSUE THREAD

**Issue by wapsi** [mautrix/slack#4]
I was setupping the bridge (compiled the git version from 2022-10-04 and tried to use pre-compiled binary as well (from here: https://mau.dev/mautrix/slack/-/pipelines?scope=branches&page=1), and right after the login the bridge crashes and throws the following error in the console where I'm running the mautrix-slack binary (Go version: go1.19.1 linux/amd64):
```
matrix-synapse@matrix:/opt/mautrix-slack/current$ ./mautrix-slack
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa9b405]

goroutine 39 [running]:
main.(*User).updateChatMute(0xc000070000, 0xc0000bc6c0, 0x1)
        /builds/mautrix/slack/user.go:747 +0x45
main.(*Portal).CreateMatrixRoom(0xc0000bc6c0, 0xc000070000, 0xc000000320, 0xc0003741e0?, 0x1)
        /builds/mautrix/slack/portal.go:370 +0xf7d
main.(*User).SyncPortals(0xc000070000, 0xc000000320, 0x9d?)
        /builds/mautrix/slack/user.go:515 +0x735
main.(*User).UpdateTeam(0xc000070000, 0xc000000320, 0x0)
        /builds/mautrix/slack/user.go:561 +0x677
main.(*User).connectTeam(0xc000070000, 0xc000000320)
        /builds/mautrix/slack/user.go:469 +0x485
main.(*User).Connect(0xc000070000)
        /builds/mautrix/slack/user.go:572 +0x345
created by main.(*SlackBridge).startUsers
        /builds/mautrix/slack/user.go:194 +0xb1
```
I think the login was successful, because the bridge created couple of rooms already, but then it keeps crashing.

Is this problem with the bridge itself, or is it maybe problem with my environment (I'm using Synapse on Debian, version: 1.68.0+buster1)?

**Comment by wapsi** [comment]
Actually it seems that every time when I try to start the bridge, it invites me to one new room and then immediately crashes.

**Comment by wapsi** [comment]
Some debug log just before the crash:
```
[Oct  4, 2022 15:32:37] [Matrix/Bot/DEBUG] req #22: PUT http://localhost:8008/_matrix/client/v3/rooms/%21xxxx:foo.bar.com/state/m.room.member/@foouser:foo.bar.com?user_id=%40slackbot%3Afoo.bar.com {"membership":"invite"}
[Oct  4, 2022 15:32:37] [Matrix/DEBUG] Starting handling of transaction 8018971 (1 PDUs)
[Oct  4, 2022 15:32:37] [Matrix/Bot/DEBUG] req #22 (/v3/rooms/!xxx:foo.bar.com/state/m.room.member/@foouser:foo.bar.com) completed in 36.48196ms with status 200 and 59 bytes of application/json body
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xaa63a5]

goroutine 62 [running]:
main.(*User).updateChatMute(0xc000432140, 0xc000438a80, 0x1)
        /opt/mautrix-slack/current/user.go:747 +0x45
main.(*Portal).CreateMatrixRoom(0xc000438a80, 0xc000432140, 0xc0003140a0, 0xc0004951a6?, 0x0)
        /opt/mautrix-slack/current/portal.go:370 +0xf7d
main.(*Portal).HandleSlackMessage(0xc000438a80, 0xc00036d950?, 0xc0003140a0, 0xc000496b00)
        /opt/mautrix-slack/current/portal.go:1354 +0x35e
main.(*User).slackMessageHandler(0xc000432140, 0xc0003140a0)
        /opt/mautrix-slack/current/user.go:415 +0x8c7
created by main.(*User).connectTeam
        /opt/mautrix-slack/current/user.go:467 +0x46b
```

**Comment by vurpo** [comment]
Should be fixed in 19422dd

**Comment by vurpo** [comment]
Yes, I see I made a mistake in the last fix. Try again now and see if it crashes with the latest commit now?

**Comment by wapsi** [comment]
So far, so good! :)
